FROM node:23-alpine AS build

ARG DATABASE_URL
ARG STORE_URL
ARG WS_URL

WORKDIR /usr/src/app

RUN apk add --no-cache openssl libc6-compat

RUN npm i -g pnpm
# Copy the necessary files from the correct locations
COPY ./packages /usr/src/app/packages
COPY ./package.json /usr/src/app/package.json  
COPY ./turbo.json /usr/src/app/turbo.json  
COPY ./pnpm-lock.yaml /usr/src/app/pnpm-lock.yaml
COPY ./pnpm-workspace.yaml /usr/src/app/pnpm-workspace.yaml
# Install dependencies
RUN pnpm install

COPY ./apps/web /usr/src/app/apps/web

WORKDIR /usr/src/app/apps/web
RUN pnpm install

WORKDIR /usr/src/app/packages/prisma
RUN DATABASE_URL=$DATABASE_URL npx prisma generate

WORKDIR /usr/src/app/packages/ui
RUN pnpm run build


WORKDIR /usr/src/app/apps/web

ENV NEXT_PUBLIC_SERVER_ENDPOINT_STORE=${STORE_URL}
ENV NEXT_PUBLIC_WS=${WS_URL}

# Build and start the client app
RUN pnpm run build 

FROM node:23-alpine AS prod

RUN apk add --no-cache openssl libc6-compat

COPY --from=build /usr/src/app/apps/web/.next/standalone ./
COPY --from=build /usr/src/app/apps/web/public ./apps/web/public
COPY --from=build /usr/src/app/apps/web/.next/static ./apps/web/.next/static
EXPOSE 3000

CMD ["node", "apps/web/server.js"]