FROM node:23-alpine

ARG DATABASE_URL

WORKDIR /usr/src/app

RUN apk add --no-cache python3 make g++ linux-headers eudev-dev

RUN apk add --no-cache openssl libc6-compat

RUN npm i -g pnpm
# Copy the necessary files from the correct locations
COPY ./packages /usr/src/app/packages
COPY ./package.json /usr/src/app/package.json  
COPY ./turbo.json /usr/src/app/turbo.json  
COPY ./pnpm-lock.yaml /usr/src/app/pnpm-lock.yaml
COPY ./pnpm-workspace.yaml /usr/src/app/pnpm-workspace.yaml
# Install dependencies
RUN pnpm install

COPY ./apps/web /usr/src/app/apps/web

WORKDIR /usr/src/app/apps/web
RUN pnpm install

WORKDIR /usr/src/app/packages/prisma
# Generate Prisma client
RUN DATABASE_URL=$DATABASE_URL npx prisma generate

WORKDIR /usr/src/app/packages/ui
RUN pnpm run build

# Expose port for the client app
EXPOSE 3000

WORKDIR /usr/src/app/apps/web
ENV NEXTAUTH_SECRET=mysecret
ENV GOOGLE_CLIENT_ID=764540667761-48sekjn798bvaa8ch8opmd5r9di3rnm2.apps.googleusercontent.com
ENV GOOGLE_CLIENT_SEC=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   
ENV DATABASE_URL="postgresql://neondb_owner:npg_8YCpWMU1tgXA@ep-late-shadow-a4kynd14-pooler.us-east-1.aws.neon.tech/neondb?sslmode=require"
ENV NEXT_PUBLIC_SERVER_ENDPOINT="http://probackend:3001/v1"
ENV NEXT_PUBLIC_WS="ws://localhost:8080"
ENV NEXT_PUBLIC_SERVER_ENDPOINT_STORE="http://localhost:3001/v1"
ENV NEXTAUTH_URL=http://localhost:3000


# Build and start the client app
RUN pnpm run build 
CMD ["pnpm", "start"]