name: CI/CD For backend
on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
    
      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        
      - name: Build and Push 
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile/Dockerfile.backend.prod
          push: true
          no-cache: true
          tags: msvaibhav4141/probo-backend:${{ github.sha }}

      - name: SSH to instance
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
             if [ "$(sudo docker ps -aq -f name=probackend)" ]; then
               echo "Stopping and removing existing container..."
               sudo docker rm -f probackend
             else
               echo "No existing container found. Proceeding to run a new one."
             fi
             sudo docker run -d \
               --name probackend \
               --network probo \
               -e REDIS_URL=${{ secrets.REDIS_URL }} \
               -e DATABASE_URL='${{ secrets.DATABASE_URL }}' \
               -e JWT_SECRET='${{ secrets.JWT }}' \
               -p 3001:3001 \
               msvaibhav4141/probo-backend:${{ github.sha }}
         